#!/usr/bin/env python3
"""
Agents.md Generator
Creates agents.md files for every directory describing its purpose and contents
"""

import os
import sys
import yaml
from pathlib import Path
sys.path.insert(0, '/home/cbwinslow/dotfiles/ai/skills')

from unified_memory.queries import search_files_content, get_directory_summary


class AgentsMdGenerator:
    """Generate agents.md files for directory documentation."""
    
    def __init__(self, base_path):
        self.base_path = Path(base_path).resolve()
        self.generated = []
    
    def generate_for_directory(self, dir_path: Path) -> str:
        """Generate agents.md content for a directory."""
        if not dir_path.exists():
            return None
        
        # Get directory info
        files = []
        subdirs = []
        code_files = []
        config_files = []
        doc_files = []
        
        for item in sorted(dir_path.iterdir()):
            if item.name.startswith('.') and item.name not in ['.config', '.github']:
                continue
            if item.name == 'agents.md':
                continue
                
            if item.is_dir():
                subdirs.append(item.name)
            else:
                files.append(item.name)
                # Categorize files
                ext = item.suffix.lower()
                if ext in ['.py', '.sh', '.bash', '.js', '.ts', '.go', '.rs']:
                    code_files.append(item.name)
                elif ext in ['.yaml', '.yml', '.json', '.toml', '.ini', '.conf']:
                    config_files.append(item.name)
                elif ext in ['.md', '.txt', '.rst']:
                    doc_files.append(item.name)
        
        # Generate content
        content = []
        content.append(f"# {dir_path.name}")
        content.append("")
        
        # Description based on directory name
        description = self._infer_description(dir_path.name, code_files, config_files)
        content.append(f"**Purpose:** {description}")
        content.append("")
        
        # Full path
        content.append(f"**Path:** `{dir_path}`")
        content.append("")
        
        # Contents overview
        content.append("## Contents")
        content.append("")
        
        if subdirs:
            content.append(f"**Subdirectories:** {len(subdirs)}")
            for d in subdirs[:10]:
                sub_desc = self._quick_subdir_desc(dir_path / d)
                content.append(f"- `{d}/` - {sub_desc}")
            if len(subdirs) > 10:
                content.append(f"- ... and {len(subdirs) - 10} more")
            content.append("")
        
        if files:
            content.append(f"**Files:** {len(files)} total")
            if code_files:
                content.append(f"- Code: {len(code_files)} files")
            if config_files:
                content.append(f"- Configs: {len(config_files)} files")
            if doc_files:
                content.append(f"- Docs: {len(doc_files)} files")
            content.append("")
        
        # Key files section
        key_files = self._identify_key_files(dir_path, files, code_files)
        if key_files:
            content.append("## Key Files")
            content.append("")
            for f, desc in key_files:
                content.append(f"- `{f}` - {desc}")
            content.append("")
        
        # AI Agent Instructions
        content.append("## AI Agent Instructions")
        content.append("")
        content.append("### When working in this directory:")
        content.append("")
        
        if code_files:
            content.append("1. **Code files:** Follow existing patterns and naming conventions")
        if config_files:
            content.append("2. **Config files:** Validate against schemas where applicable")
        if '.sh' in str(code_files):
            content.append("3. **Shell scripts:** Use `set -euo pipefail` for error handling")
        if '.py' in str(code_files):
            content.append("4. **Python:** Follow PEP 8, add docstrings for functions")
        
        content.append("")
        content.append("### Common Tasks:")
        content.append("")
        
        # Infer common tasks based on directory type
        tasks = self._infer_common_tasks(dir_path.name, code_files)
        for i, task in enumerate(tasks, 1):
            content.append(f"{i}. {task}")
        
        content.append("")
        
        # Related directories
        if subdirs:
            content.append("### Related Directories:")
            content.append("")
            for d in subdirs[:5]:
                content.append(f"- See [`{d}/`]({d}/agents.md) for related functionality")
            content.append("")
        
        # Footer
        content.append("---")
        content.append("*Generated by cbw-agents-md generator*")
        
        return '\n'.join(content)
    
    def _infer_description(self, dir_name: str, code_files: list, config_files: list) -> str:
        """Infer directory description from name and contents."""
        descriptions = {
            'scripts': 'Executable scripts and automation tools',
            'skills': 'AI agent skills and capabilities',
            'agents': 'AI agent configurations and definitions',
            'config': 'Configuration files and settings',
            'docs': 'Documentation and guides',
            'templates': 'Reusable templates and boilerplate',
            'workflows': 'Workflow definitions and processes',
            'shared': 'Shared resources used across components',
            'utils': 'Utility functions and helpers',
            'lib': 'Library code and modules',
            'src': 'Source code',
            'tests': 'Test files and test data',
            'ai': 'AI-related configurations and tools',
            'shell': 'Shell scripts and utilities',
            'docker': 'Docker configurations and scripts',
            'db': 'Database-related files',
            'migrations': 'Database migration scripts',
        }
        
        # Try exact match
        if dir_name.lower() in descriptions:
            return descriptions[dir_name.lower()]
        
        # Try partial match
        for key, desc in descriptions.items():
            if key in dir_name.lower():
                return desc
        
        # Default based on contents
        if code_files and config_files:
            return f"Mixed code and configuration ({len(code_files)} code, {len(config_files)} config files)"
        elif code_files:
            return f"Code directory with {len(code_files)} source files"
        elif config_files:
            return f"Configuration directory with {len(config_files)} config files"
        elif not code_files and not config_files and not config_files:
            return "Directory container (subdirectories only)"
        else:
            return f"Directory with {len(code_files) + len(config_files)} files"
    
    def _quick_subdir_desc(self, subdir_path: Path) -> str:
        """Generate quick description for subdirectory."""
        name = subdir_path.name.lower()
        
        if any(x in name for x in ['test', 'spec']):
            return "Tests"
        elif any(x in name for x in ['doc', 'guide', 'help']):
            return "Documentation"
        elif any(x in name for x in ['config', 'setting']):
            return "Configuration"
        elif any(x in name for x in ['script', 'bin', 'cmd']):
            return "Scripts"
        elif any(x in name for x in ['asset', 'resource', 'static']):
            return "Resources"
        else:
            return "Related files"
    
    def _identify_key_files(self, dir_path: Path, all_files: list, code_files: list) -> list:
        """Identify key files and their purposes."""
        key_files = []
        
        for f in all_files:
            # Main entry points
            if f in ['main.py', 'index.js', 'app.py', 'server.py', 'cli.py']:
                key_files.append((f, "Main entry point"))
            elif f == '__init__.py':
                key_files.append((f, "Python package initializer"))
            elif f == 'README.md':
                key_files.append((f, "Documentation"))
            elif f in ['requirements.txt', 'package.json', 'Cargo.toml', 'go.mod']:
                key_files.append((f, "Dependency manifest"))
            elif f in ['Dockerfile', 'docker-compose.yml']:
                key_files.append((f, "Docker configuration"))
            elif f == 'Makefile':
                key_files.append((f, "Build automation"))
            elif f == 'setup.py' or f == 'pyproject.toml':
                key_files.append((f, "Package setup"))
            elif 'config' in f.lower() and f.endswith(('.yaml', '.yml', '.json', '.py')):
                key_files.append((f, "Configuration"))
            elif f.endswith('.sh') and ('setup' in f or 'install' in f or 'run' in f):
                key_files.append((f, "Setup/execution script"))
            elif f == 'SKILL.md':
                key_files.append((f, "AI skill definition"))
            elif f == '.gitignore':
                key_files.append((f, "Git ignore rules"))
        
        # Add first code file as example if no key files identified
        if not key_files and code_files:
            key_files.append((code_files[0], "Primary code file"))
        
        return key_files[:8]  # Limit to 8 key files
    
    def _infer_common_tasks(self, dir_name: str, code_files: list) -> list:
        """Infer common tasks for AI agents."""
        tasks = []
        
        # Base tasks
        if any(f.endswith('.sh') for f in code_files):
            tasks.append("Add error handling with `set -euo pipefail`")
            tasks.append("Ensure scripts are executable (`chmod +x`)")
        
        if any(f.endswith('.py') for f in code_files):
            tasks.append("Add docstrings to functions")
            tasks.append("Follow PEP 8 style guidelines")
            tasks.append("Add type hints where appropriate")
        
        if dir_name in ['scripts', 'bin']:
            tasks.append("Add usage examples in comments")
            tasks.append("Validate with shellcheck (bash) or pylint (python)")
        
        if dir_name in ['skills']:
            tasks.append("Ensure SKILL.md is present and up to date")
            tasks.append("Test skill integration with agents")
        
        if dir_name in ['agents']:
            tasks.append("Validate agent YAML configuration")
            tasks.append("Ensure required skills are available")
        
        if dir_name in ['config', 'configs']:
            tasks.append("Validate configuration syntax")
            tasks.append("Document configuration options")
        
        if dir_name in ['docs', 'documentation']:
            tasks.append("Keep documentation synchronized with code changes")
            tasks.append("Use clear headings and code examples")
        
        if not tasks:
            tasks.append("Follow existing code patterns and conventions")
            tasks.append("Add comments explaining complex logic")
            tasks.append("Update this agents.md when structure changes")
        
        return tasks[:6]  # Limit to 6 tasks
    
    def generate_recursive(self, max_depth: int = 3, dry_run: bool = False) -> list:
        """Generate agents.md for all directories recursively."""
        generated = []
        
        for root, dirs, files in os.walk(self.base_path):
            # Calculate depth
            depth = len(Path(root).relative_to(self.base_path).parts)
            if depth > max_depth:
                continue
            
            # Skip hidden and special directories
            dirs[:] = [d for d in dirs if not d.startswith('.') or d in ['.config', '.github']]
            dirs[:] = [d for d in dirs if d not in ['__pycache__', 'node_modules', 'venv', '.venv', 'env']]
            
            dir_path = Path(root)
            content = self.generate_for_directory(dir_path)
            
            if content:
                agents_md_path = dir_path / 'agents.md'
                
                if dry_run:
                    print(f"Would create: {agents_md_path}")
                    generated.append(str(agents_md_path))
                else:
                    with open(agents_md_path, 'w') as f:
                        f.write(content)
                    print(f"Created: {agents_md_path}")
                    generated.append(str(agents_md_path))
        
        return generated
    
    def update_existing(self) -> list:
        """Update existing agents.md files."""
        updated = []
        
        for root, dirs, files in os.walk(self.base_path):
            if 'agents.md' in files:
                dir_path = Path(root)
                content = self.generate_for_directory(dir_path)
                
                if content:
                    agents_md_path = dir_path / 'agents.md'
                    with open(agents_md_path, 'w') as f:
                        f.write(content)
                    print(f"Updated: {agents_md_path}")
                    updated.append(str(agents_md_path))
        
        return updated


def main():
    import argparse
    parser = argparse.ArgumentParser(description='Generate agents.md files')
    parser.add_argument('path', nargs='?', default='.', help='Base path to process')
    parser.add_argument('--recursive', '-r', action='store_true', help='Process recursively')
    parser.add_argument('--depth', '-d', type=int, default=3, help='Max recursion depth')
    parser.add_argument('--dry-run', action='store_true', help='Show what would be created')
    parser.add_argument('--update', '-u', action='store_true', help='Update existing agents.md files')
    args = parser.parse_args()
    
    generator = AgentsMdGenerator(args.path)
    
    if args.update:
        files = generator.update_existing()
        print(f"\nUpdated {len(files)} agents.md files")
    elif args.recursive:
        files = generator.generate_recursive(max_depth=args.depth, dry_run=args.dry_run)
        print(f"\n{'Would create' if args.dry_run else 'Created'} {len(files)} agents.md files")
    else:
        # Single directory
        content = generator.generate_for_directory(Path(args.path))
        if content:
            print(content)


if __name__ == '__main__':
    main()
